export const communities = [
  {
    id: 'c-001',
    name: 'Canyon Ridge',
    builder: 'Summit Homes',
    metro: 'Phoenix',
    submarket: 'Queen Creek',
    address: '1020 E Canyon Ridge Dr, Queen Creek, AZ',
    coordinates: { lat: 33.248, lng: -111.635 },
    lotCount: { total: 320, delivered: 180, future: 140 },
    productType: 'Single-Family Detached',
    priceBand: '$380K - $520K',
    buyerProfile: 'Move-up families seeking resort-style amenities',
    notes: 'Phase 2 delivering utilities by Q4.',
  },
  {
    id: 'c-002',
    name: 'Saguaro Vista',
    builder: 'MarketField Homes',
    metro: 'Phoenix',
    submarket: 'Mesa',
    address: '2331 W Vista Way, Mesa, AZ',
    coordinates: { lat: 33.422, lng: -111.823 },
    lotCount: { total: 210, delivered: 120, future: 90 },
    productType: 'Townhome',
    priceBand: '$320K - $410K',
    buyerProfile: 'First-time buyers seeking lock-and-leave convenience',
    notes: 'Leasing model center through summer.',
  },
];

export const competitors = [
  {
    id: 'comp-001',
    name: 'Silver Trails',
    builder: 'Suncrest Builders',
    website: 'https://suncrest.com/silver-trails',
    metro: 'Phoenix',
    submarket: 'Queen Creek',
    address: '411 W Silver Trails, Queen Creek, AZ',
    coordinates: { lat: 33.236, lng: -111.656 },
    distanceMiles: 2.4,
    productType: 'Single-Family Detached',
    active: true,
    tags: ['production', 'value'],
    priceRange: '$360K - $480K',
  },
  {
    id: 'comp-002',
    name: 'Skyline Estates',
    builder: 'BlueRock Communities',
    website: 'https://bluerock.com/skyline-estates',
    metro: 'Phoenix',
    submarket: 'Queen Creek',
    address: '77 E Skyline Rd, Queen Creek, AZ',
    coordinates: { lat: 33.252, lng: -111.61 },
    distanceMiles: 3.1,
    productType: 'Single-Family Detached',
    active: true,
    tags: ['premium'],
    priceRange: '$430K - $580K',
  },
  {
    id: 'comp-003',
    name: 'Oak Grove Villas',
    builder: 'Vista Living',
    website: 'https://vistaliving.com/oak-grove',
    metro: 'Phoenix',
    submarket: 'Mesa',
    address: '1290 N Oak Grove Rd, Mesa, AZ',
    coordinates: { lat: 33.435, lng: -111.79 },
    distanceMiles: 6.9,
    productType: 'Townhome',
    active: true,
    tags: ['luxury'],
    priceRange: '$390K - $470K',
  },
];

export const plans = [
  {
    communityId: 'c-001',
    planName: 'Saguaro',
    squareFeet: 1850,
    beds: 3,
    baths: 2,
    garage: 2,
    stories: 1,
    basePrice: 399990,
    status: 'active',
    url: 'https://summit.com/canyon-ridge/saguaro',
  },
  {
    communityId: 'c-001',
    planName: 'Mesquite',
    squareFeet: 2250,
    beds: 4,
    baths: 2.5,
    garage: 3,
    stories: 2,
    basePrice: 449990,
    status: 'active',
    url: 'https://summit.com/canyon-ridge/mesquite',
  },
  {
    communityId: 'c-001',
    planName: 'Ocotillo',
    squareFeet: 2600,
    beds: 4,
    baths: 3,
    garage: 3,
    stories: 2,
    basePrice: 489990,
    status: 'active',
    url: 'https://summit.com/canyon-ridge/ocotillo',
  },
  {
    communityId: 'c-001',
    planName: 'Ironwood',
    squareFeet: 2850,
    beds: 5,
    baths: 3.5,
    garage: 3,
    stories: 2,
    basePrice: 529990,
    status: 'paused',
    url: 'https://summit.com/canyon-ridge/ironwood',
  },
  {
    communityId: 'c-002',
    planName: 'Agave',
    squareFeet: 1650,
    beds: 3,
    baths: 2.5,
    garage: 2,
    stories: 2,
    basePrice: 339990,
    status: 'active',
    url: 'https://marketfieldhomes.com/saguaro-vista/agave',
  },
  {
    communityId: 'comp-001',
    planName: 'Trailhead',
    squareFeet: 1750,
    beds: 3,
    baths: 2,
    garage: 2,
    stories: 1,
    basePrice: 379900,
    status: 'active',
  },
  {
    communityId: 'comp-002',
    planName: 'Summit',
    squareFeet: 2300,
    beds: 4,
    baths: 3,
    garage: 3,
    stories: 2,
    basePrice: 509900,
    status: 'active',
  },
];

export const inventoryHomes = [
  {
    communityId: 'c-001',
    planName: 'Mesquite',
    lot: 'Lot 42',
    address: '2041 E Canyon Ridge Dr',
    squareFeet: 2250,
    beds: 4,
    baths: 2.5,
    garage: 3,
    stage: 'frame',
    price: 459990,
    deliveryDate: '2024-07-15',
    notes: '$10K design studio credit',
  },
  {
    communityId: 'c-001',
    planName: 'Ocotillo',
    lot: 'Lot 61',
    address: '2057 E Canyon Ridge Dr',
    squareFeet: 2600,
    beds: 4,
    baths: 3,
    garage: 3,
    stage: 'trim',
    price: 499990,
    deliveryDate: '2024-05-30',
    notes: 'Included RV gate',
  },
  {
    communityId: 'comp-001',
    planName: 'Trailhead',
    lot: 'Lot 13',
    address: '414 Silver Trails Ave',
    squareFeet: 1780,
    beds: 3,
    baths: 2,
    garage: 2,
    stage: 'drywall',
    price: 389900,
    deliveryDate: '2024-04-20',
    notes: '',
  },
];

export const salesRecords = [
  {
    id: 'sale-001',
    source: 'MLS',
    type: 'resale',
    address: '921 W Grove St',
    communityId: 'c-001',
    closeDate: '2024-02-14',
    contractDate: '2023-12-12',
    squareFeet: 2100,
    beds: 4,
    baths: 2.5,
    soldPrice: 435000,
    dom: 32,
  },
  {
    id: 'sale-002',
    source: 'Internal',
    type: 'new',
    address: '2037 E Canyon Ridge Dr',
    communityId: 'c-001',
    closeDate: '2024-01-21',
    contractDate: '2023-11-10',
    squareFeet: 2250,
    beds: 4,
    baths: 2.5,
    soldPrice: 452000,
    dom: 18,
  },
  {
    id: 'sale-003',
    source: 'Zonda',
    type: 'new',
    address: '36 W Vervain Rd',
    communityId: 'comp-001',
    closeDate: '2024-02-02',
    contractDate: '2023-11-24',
    squareFeet: 1950,
    beds: 3,
    baths: 2,
    soldPrice: 410000,
    dom: 24,
  },
  {
    id: 'sale-004',
    source: 'MLS',
    type: 'resale',
    address: '442 Skyline Ridge',
    communityId: 'comp-002',
    closeDate: '2024-01-15',
    squareFeet: 2380,
    beds: 4,
    baths: 3,
    soldPrice: 515000,
    dom: 40,
  },
  {
    id: 'sale-005',
    source: 'MLS',
    type: 'resale',
    address: '5524 E Grand Ave',
    communityId: 'c-002',
    closeDate: '2024-01-28',
    squareFeet: 1700,
    beds: 3,
    baths: 2.5,
    soldPrice: 365000,
    dom: 27,
  },
];

export const startRecommendations = [
  {
    communityId: 'c-001',
    date: '2024-02-15',
    planMix: [
      { label: 'Entry (1,700-1,950 SF)', count: 3, beds: '3-4', baths: '2-2.5' },
      { label: 'Core (1,950-2,300 SF)', count: 5, beds: '4', baths: '2.5-3' },
      { label: 'Upsize (2,300-2,800 SF)', count: 2, beds: '4-5', baths: '3+' },
    ],
    startCounts: [
      { label: 'Now', total: 5 },
      { label: 'Next 60 days', total: 4 },
      { label: 'Next 90+ days', total: 3 },
    ],
    pricing: [
      { label: 'Entry', priceRange: '$380K-$410K', ppsf: '$195', positioning: 'Value leader' },
      { label: 'Core', priceRange: '$420K-$470K', ppsf: '$205', positioning: 'In-line with market' },
      { label: 'Upsize', priceRange: '$480K-$540K', ppsf: '$210', positioning: 'Premium priced' },
    ],
    targetSupplyMonths: 4,
    absorption: 3,
    summary:
      'Buyers within 5 miles are most active between $380K-$450K and 1,900-2,300 SF. Four-bed plans with lofts have the fastest turns. Maintain ~12 specs with emphasis on 4-bed product near $200/SF to support a 4-month supply.',
  },
];

export const websiteLogs = [
  {
    id: 'log-1',
    communityId: 'comp-001',
    url: 'https://suncrest.com/silver-trails',
    lastFetch: '2024-02-10 08:12',
    plansParsed: 4,
    inventoryParsed: 3,
    status: 'success',
    notes: '',
  },
  {
    id: 'log-2',
    communityId: 'comp-002',
    url: 'https://bluerock.com/skyline-estates',
    lastFetch: '2024-02-12 09:41',
    plansParsed: 5,
    inventoryParsed: 2,
    status: 'warning',
    notes: 'Missing pricing for 2 plans',
  },
];

export const dataSources = [
  {
    id: 'ds-1',
    name: 'MLS Export - Phoenix East Valley',
    type: 'CSV',
    lastSync: '2024-02-14 19:10',
    recordsUpdated: 248,
    status: 'healthy',
  },
  {
    id: 'ds-2',
    name: 'Zonda Builder Insights',
    type: 'XLSX',
    lastSync: '2024-02-13 07:42',
    recordsUpdated: 98,
    status: 'needs review',
  },
];
