#!/usr/bin/env python3
"""Plan 2 execution helper for the March Madness research blueprint.

This script turns the six roadmap phases into concrete, trackable tasks.
"""
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

PHASES = {
    "phase1": {
        "name": "Infrastructure and data acquisition",
        "inputs": [
            "Data source credentials/URLs",
            "Schema contract for team, player, game, market, and injury tables",
        ],
        "outputs": [
            "warehouse/feature_dictionary.md",
            "warehouse/data_validation_report.md",
        ],
    },
    "phase2": {
        "name": "Historical modeling and benchmark establishment",
        "inputs": [
            "Historical tournament dataset",
            "Feature store from phase 1",
        ],
        "outputs": [
            "models/benchmark_report.md",
            "models/calibration_summary.md",
        ],
    },
    "phase3": {
        "name": "Pre-Selection Sunday readiness",
        "inputs": [
            "Upset archetype definitions",
            "Round weighting policies",
        ],
        "outputs": [
            "readiness/methodology_handbook.md",
            "readiness/matchup_dossier_template.md",
        ],
    },
    "phase4": {
        "name": "Selection Sunday ingestion and provisional forecasting",
        "inputs": [
            "Official bracket structure",
            "Current model artifacts from phase 2",
        ],
        "outputs": [
            "forecast/provisional_brackets.md",
            "forecast/sensitivity_report.md",
        ],
    },
    "phase5": {
        "name": "Final update and pick lock",
        "inputs": [
            "Verified injury/availability updates",
            "Latest market movement snapshot",
        ],
        "outputs": [
            "lock/official_submission_bracket.md",
            "lock/confidence_ledger.md",
        ],
    },
    "phase6": {
        "name": "Post-mortem and model revision",
        "inputs": [
            "Tournament outcomes",
            "Prediction logs",
        ],
        "outputs": [
            "retrospective/error_taxonomy.md",
            "retrospective/2027_backlog.md",
        ],
    },
}


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def initialize(workspace: Path) -> None:
    workspace.mkdir(parents=True, exist_ok=True)
    for phase, meta in PHASES.items():
        phase_dir = workspace / phase
        phase_dir.mkdir(parents=True, exist_ok=True)
        for output in meta["outputs"]:
            out_path = phase_dir / output
            out_path.parent.mkdir(parents=True, exist_ok=True)
            if not out_path.exists():
                out_path.write_text(
                    f"# {meta['name']}\n\n"
                    f"Generated by run_plan2.py at {utc_now()}.\n\n"
                    "## TODO\n"
                    "- Fill this artifact with phase-specific analysis and decisions.\n",
                    encoding="utf-8",
                )

    ledger_path = workspace / "plan2_ledger.json"
    if not ledger_path.exists():
        ledger = {
            "created_at": utc_now(),
            "phases": {
                k: {"name": v["name"], "status": "pending", "updated_at": None}
                for k, v in PHASES.items()
            },
        }
        ledger_path.write_text(json.dumps(ledger, indent=2), encoding="utf-8")


def mark_status(workspace: Path, phase: str, status: str) -> None:
    if phase not in PHASES:
        raise SystemExit(f"Unknown phase '{phase}'. Expected one of: {', '.join(PHASES)}")

    ledger_path = workspace / "plan2_ledger.json"
    if not ledger_path.exists():
        raise SystemExit("Ledger not found. Run 'init' first.")

    ledger = json.loads(ledger_path.read_text(encoding="utf-8"))
    ledger["phases"][phase]["status"] = status
    ledger["phases"][phase]["updated_at"] = utc_now()
    ledger_path.write_text(json.dumps(ledger, indent=2), encoding="utf-8")


def show_status(workspace: Path) -> None:
    ledger_path = workspace / "plan2_ledger.json"
    if not ledger_path.exists():
        raise SystemExit("Ledger not found. Run 'init' first.")

    ledger = json.loads(ledger_path.read_text(encoding="utf-8"))
    print("Plan 2 execution status")
    print("=" * 28)
    for phase, data in ledger["phases"].items():
        print(f"{phase}: {data['status']} ({data['name']})")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Execute and track March Madness Plan 2 phases")
    parser.add_argument(
        "--workspace",
        default="plan2/workspace",
        help="Directory where phase artifacts and ledger are stored",
    )

    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("init", help="Initialize Plan 2 artifacts and phase ledger")

    mark = sub.add_parser("mark", help="Mark phase status")
    mark.add_argument("phase", choices=sorted(PHASES.keys()))
    mark.add_argument("status", choices=["pending", "in_progress", "completed"])

    sub.add_parser("status", help="Print current phase status from ledger")
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    workspace = Path(args.workspace)

    if args.cmd == "init":
        initialize(workspace)
        print(f"Initialized Plan 2 workspace: {workspace}")
    elif args.cmd == "mark":
        mark_status(workspace, args.phase, args.status)
        print(f"Updated {args.phase} -> {args.status}")
    elif args.cmd == "status":
        show_status(workspace)


if __name__ == "__main__":
    main()
